// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkflsccbuzecubyjvxqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrZmxzY2NidXplY3VieWp2eHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTkzOTgsImV4cCI6MjA1OTc5NTM5OH0.6-HB2o1PPpQ_qHnNljHdLOZnNoBAfQvkuYQrS9a9opw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);